server:
  port: 3998

eureka:
  instance:
    hostname: ${hostname}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone:
        - ${protocol}://${eureka.instance.hostname}:${server.port}/eureka/

  server:
    waitTimeInMsWhenSyncEmpty: 30000